clone_depth: 10

version: "{build}"

branches:
  only:
  - master

environment:
  fast_finish: true
  matrix:
    - nodejs_version: "10"
      platform: x86

build: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install yarn -g
  - yarn

before_test:
  - set "PATH=C:\MinGW\msys\1.0\bin;%PATH%"
  - set "CHROME_PATH=%CD%\chrome-win32\chrome.exe"
  - bash ./lighthouse-core/scripts/download-chrome.sh
  - yarn build-all

test_script:
  - node --version
  - npm --version
  - yarn --version
  - which yarn
  # Appveyor protocol timeouts are unusually common.
  # We retry our smoketests 3 times for this reason, so do the same for CLI tests that launch Chrome.
  - yarn unit-cli || yarn unit-cli || yarn unit-cli

cache:
  #- chrome-win32 -> appveyor.yml,package.json
  - node_modules -> appveyor.yml,package.json,yarn.lock
  - '%LOCALAPPDATA%\Yarn -> appveyor.yml,package.json,yarn.lock'
