name: 💡🏠

on:
  push:
  pull_request: # run on all PRs, not just PRs to a particular branch

jobs:
  # `unit` includes just unit and proto tests.
  unit:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: unit - ${{ matrix.os ==  'ubuntu-latest' && 'Ubuntu' || 'Windows' }}

    steps:
    - name: git clone
      uses: actions/checkout@v2
      with:
        # Depth of at least 2 for codecov coverage diffs. See https://github.com/GoogleChrome/lighthouse/pull/12079
        fetch-depth: 2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Set up protoc
      uses: arduino/setup-protoc@64c0c85d18e984422218383b81c52f8b077404d3
      with:
        version: '3.7.1'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install protobuf==3.7.1

    - run: yarn install --frozen-lockfile --network-timeout 1000000

    - run: yarn test-proto # Run before unit-core because the roundtrip json is needed for proto tests.

    - run: sudo apt-get install xvfb
      if: matrix.os == 'ubuntu-latest'

    - name: yarn unit
      run: |
        xvfb-run --auto-servernum yarn unit:cicoverage
        yarn c8 report --reporter text-lcov > unit-coverage.lcov
      if: matrix.os == 'ubuntu-latest'

    # Fail if any changes were written to any source files or generated untracked files (ex, from -GA).
    - run: git add -A && git diff --cached --exit-code
